// 名古屋・飛驒家族旅行行程資料
// 2026年3月25日 - 3月30日

export const TRIP_DATA = {
  title: "🌸 名古屋・飛驒 家族旅行",
  subtitle: "2026年3月25日 – 3月30日",
  days: [
    {
      id: 1,
      date: "3/25",
      weekday: "週三",
      emoji: "✈️",
      title: "出發 → 抵達名古屋",
      color: "#E8527A",
      items: [
        {
          id: "d1_1",
          time: "14:45",
          type: "transport",
          emoji: "✈️",
          title: "台中清泉崗機場出發",
          subtitle: "CI-161 台中 → 名古屋中部",
          mapQuery: "台中清泉崗機場",
          note: "",
        },
        {
          id: "d1_2",
          time: "20:25",
          type: "arrival",
          emoji: "🛬",
          title: "中部國際機場（Centrair）抵達",
          subtitle: "入境、領行李、換日幣",
          mapQuery: "中部国際空港 セントレア",
          note: "",
        },
        {
          id: "d1_3",
          time: "晚餐",
          type: "food",
          emoji: "🍜",
          title: "Hanzo Seimen 獅子丸拉麵",
          subtitle: "機場 4F Sky Town 商業設施內",
          mapQuery: "半蔵製麺 獅子丸 中部国際空港",
          note: "",
        },
        {
          id: "d1_4",
          time: "住宿",
          type: "hotel",
          emoji: "🏨",
          title: "Comfort Hotel 中部國際機場",
          subtitle: "機場島步行 10 分 • 含早餐",
          mapQuery: "コンフォートホテル中部国際空港",
          note: "",
        },
      ],
      routes: [
        {
          from: "機場入境大廳",
          to: "Comfort Hotel",
          duration: "約 10 分",
          mapUrl:
            "https://www.google.com/maps/dir/中部国際空港/コンフォートホテル中部国際空港",
        },
      ],
    },
    {
      id: 2,
      date: "3/26",
      weekday: "週四",
      emoji: "🌸",
      title: "租車 → 戶田川 → 長島溫泉",
      color: "#FF8C42",
      items: [
        {
          id: "d2_1",
          time: "09:00",
          type: "transport",
          emoji: "🚗",
          title: "Times Car Rental 取車",
          subtitle: "中部國際機場 Times 租車取車處",
          mapQuery: "タイムズカー 中部国際空港店",
          note: "",
        },
        {
          id: "d2_2",
          time: "上午",
          type: "activity",
          emoji: "🌳",
          title: "戶田川綠地公園",
          subtitle: "賞春、散步、兒童廣場",
          mapQuery: "戸田川緑地 名古屋市",
          note: "",
        },
        {
          id: "d2_3",
          time: "午餐",
          type: "food",
          emoji: "🍣",
          title: "午餐（自由選擇）",
          subtitle: "💡 推薦：回程路上稻澤市的「麵屋しらかわ」名古屋系清湯拉麵",
          mapQuery: "麺屋しらかわ 稲沢",
          isRecommendation: true,
          note: "",
        },
        {
          id: "d2_4",
          time: "下午",
          type: "activity",
          emoji: "🎢",
          title: "Nagashima 長島溫泉樂園",
          subtitle: "ナガシマスパーランド • 遊樂設施、溫泉",
          mapQuery: "ナガシマスパーランド",
          note: "",
        },
        {
          id: "d2_5",
          time: "下午",
          type: "shopping",
          emoji: "🛍️",
          title: "三井 Outlet Park 長島",
          subtitle: "與溫泉樂園相連 • Jazz Dream Nagashima",
          mapQuery: "三井アウトレットパーク ジャズドリーム長島",
          note: "",
        },
        {
          id: "d2_6",
          time: "晚餐",
          type: "food",
          emoji: "🍖",
          title: "矢場とん（矢場豬排）",
          subtitle: "Outlet 店 • 名古屋名物味噌豬排",
          mapQuery: "矢場とん ジャズドリーム長島店",
          note: "",
        },
        {
          id: "d2_7",
          time: "住宿",
          type: "hotel",
          emoji: "🏠",
          title: "Airbnb 民宿",
          subtitle: "豐田技術館附近",
          mapQuery: "トヨタ産業技術記念館 名古屋",
          note: "",
        },
      ],
      routes: [
        {
          from: "機場",
          to: "戶田川公園",
          duration: "約 45 分",
          mapUrl: "https://www.google.com/maps/dir/中部国際空港/戸田川緑地",
        },
        {
          from: "戶田川公園",
          to: "長島 Outlet",
          duration: "約 25 分",
          mapUrl:
            "https://www.google.com/maps/dir/戸田川緑地/三井アウトレットパーク+ジャズドリーム長島",
        },
        {
          from: "長島 Outlet",
          to: "民宿（豐田技術館附近）",
          duration: "約 15 分",
          mapUrl:
            "https://www.google.com/maps/dir/三井アウトレットパーク+ジャズドリーム長島/トヨタ産業技術記念館",
        },
      ],
    },
    {
      id: 3,
      date: "3/27",
      weekday: "週五",
      emoji: "🏯",
      title: "名古屋城 → 大須 → 郡上八幡",
      color: "#4ECDC4",
      items: [
        {
          id: "d3_1",
          time: "上午",
          type: "activity",
          emoji: "🏯",
          title: "名古屋城",
          subtitle: "日本三大名城之一 • 天守閣、本丸御殿",
          mapQuery: "名古屋城",
          note: "",
        },
        {
          id: "d3_2",
          time: "上午",
          type: "activity",
          emoji: "🌸",
          title: "名城公園賞櫻",
          subtitle: "護城河旁 • 名古屋最佳賞花勝地之一",
          mapQuery: "名城公園",
          note: "",
        },
        {
          id: "d3_3",
          time: "午餐",
          type: "food",
          emoji: "🍡",
          title: "大須商店街",
          subtitle: "名古屋最熱鬧商店街 • 小吃、古著、電器、神社",
          mapQuery: "大須商店街",
          note: "",
        },
        {
          id: "d3_4",
          time: "下午",
          type: "hotel",
          emoji: "🏨",
          title: "Check-in Fairfield by Marriott Gifu Gujo",
          subtitle: "郡上八幡萬楓飯店 • 飯店隔壁有溫泉館",
          mapQuery: "フェアフィールド・バイ・マリオット岐阜郡上",
          note: "",
        },
        {
          id: "d3_5",
          time: "傍晚",
          type: "activity",
          emoji: "♨️",
          title: "溫泉館泡湯 + 晚餐",
          subtitle: "飯店隔壁温泉・グリーンホテルyes郡上八幡",
          mapQuery: "グリーンホテルYES郡上八幡",
          note: "",
        },
      ],
      routes: [
        {
          from: "民宿（豐田技術館）",
          to: "名古屋城",
          duration: "約 10 分",
          mapUrl:
            "https://www.google.com/maps/dir/トヨタ産業技術記念館/名古屋城",
        },
        {
          from: "名古屋城",
          to: "大須商店街",
          duration: "約 10 分",
          mapUrl: "https://www.google.com/maps/dir/名古屋城/大須商店街",
        },
        {
          from: "大須商店街",
          to: "郡上八幡萬楓飯店",
          duration: "約 1 小時 15 分",
          mapUrl:
            "https://www.google.com/maps/dir/大須商店街/フェアフィールド・バイ・マリオット岐阜郡上",
        },
      ],
    },
    {
      id: 4,
      date: "3/28",
      weekday: "週六",
      emoji: "🥩",
      title: "郡上城下町 → 高山老街",
      color: "#9B59B6",
      items: [
        {
          id: "d4_1",
          time: "上午",
          type: "activity",
          emoji: "🎏",
          title: "郡上八幡城下町",
          subtitle: "錦鯉小徑・食品模型街・郡上八幡城",
          mapQuery: "郡上八幡 城下町",
          note: "",
        },
        {
          id: "d4_2",
          time: "午餐",
          type: "food",
          emoji: "🍜",
          title: "午餐（推薦：中華そば 水舟）",
          subtitle: "💡 郡上八幡最有名的中華拉麵老店，在地人都愛",
          mapQuery: "中華そば 水舟 郡上八幡",
          isRecommendation: true,
          note: "",
        },
        {
          id: "d4_3",
          time: "下午",
          type: "activity",
          emoji: "🏘️",
          title: "高山老街（三町筋古い町並み）",
          subtitle: "江戶時代保存街道 • 酒屏、醬油屋、咖啡店",
          mapQuery: "高山 三町筋 古い町並み",
          note: "",
        },
        {
          id: "d4_4",
          time: "下午",
          type: "food",
          emoji: "🍣",
          title: "飛驒牛握壽司",
          subtitle: "老街兩旁攤位均有販售 • 必吃！",
          mapQuery: "高山 飛騨牛 握り寿司",
          note: "",
        },
        {
          id: "d4_5",
          time: "晚餐",
          type: "food",
          emoji: "🥩",
          title: "飛驒牛燒肉（推薦：焼肉 飛騨）",
          subtitle: "💡 高山站旁步行可達・特上カルビ必點・評分 4.2★",
          mapQuery: "焼肉飛騨 高山",
          isRecommendation: true,
          note: "",
        },
        {
          id: "d4_6",
          time: "住宿",
          type: "hotel",
          emoji: "🏨",
          title: "Hotel Amanek Hidatakayama",
          subtitle: "高山站旁步行 3 分 • 新型商務飯店",
          mapQuery: "ホテルアマネク飛騨高山",
          note: "",
        },
      ],
      routes: [
        {
          from: "郡上八幡萬楓飯店",
          to: "郡上城下町",
          duration: "約 10 分",
          mapUrl:
            "https://www.google.com/maps/dir/フェアフィールド・バイ・マリオット岐阜郡上/郡上八幡+城下町",
        },
        {
          from: "郡上城下町",
          to: "Hotel Amanek 高山",
          duration: "約 1 小時",
          mapUrl:
            "https://www.google.com/maps/dir/郡上八幡+城下町/ホテルアマネク飛騨高山",
        },
      ],
    },
    {
      id: 5,
      date: "3/29",
      weekday: "週日",
      emoji: "🐑",
      title: "牧歌之里 → 三光神社 → 常滑",
      color: "#2ECC71",
      items: [
        {
          id: "d5_1",
          time: "上午",
          type: "activity",
          emoji: "🐑",
          title: "牧歌之里",
          subtitle: "玩雪・餵羊・田園風景・親子同樂",
          mapQuery: "牧歌の里 岐阜",
          note: "",
        },
        {
          id: "d5_2",
          time: "午餐",
          type: "food",
          emoji: "🍽️",
          title: "牧歌之里園內餐廳",
          subtitle: "💡 推薦：飛驒牛鐵板燒套餐（需現場排隊）",
          mapQuery: "牧歌の里 レストラン",
          note: "",
        },
        {
          id: "d5_3",
          time: "下午",
          type: "activity",
          emoji: "⛩️",
          title: "三光稻荷神社",
          subtitle: "洗錢祈福（錢洗弁財天）・粉紅愛心牆・求緣",
          mapQuery: "三光稲荷神社 犬山",
          note: "",
        },
        {
          id: "d5_4",
          time: "下午",
          type: "shopping",
          emoji: "🎂",
          title: "幫妹妹買生日禮物 🎁",
          subtitle: "犬山市區 or 常滑購物・這是最重要的任務！",
          mapQuery: "犬山市 ショッピング",
          note: "",
        },
        {
          id: "d5_5",
          time: "晚上",
          type: "shopping",
          emoji: "🛒",
          title: "常滑 AEON 購物中心",
          subtitle: "晚餐 + 購物 + 最後採買",
          mapQuery: "イオンモール常滑",
          note: "",
        },
        {
          id: "d5_6",
          time: "住宿",
          type: "hotel",
          emoji: "🏨",
          title: "東橫INN 中部國際機場 1 號館",
          subtitle: "機場旁 • 明天方便還車出發",
          mapQuery: "東横INN中部国際空港1号館",
          note: "",
        },
      ],
      routes: [
        {
          from: "Hotel Amanek 高山",
          to: "牧歌之里",
          duration: "約 50 分",
          mapUrl:
            "https://www.google.com/maps/dir/ホテルアマネク飛騨高山/牧歌の里+岐阜",
        },
        {
          from: "牧歌之里",
          to: "三光稻荷神社",
          duration: "約 1 小時 15 分",
          mapUrl:
            "https://www.google.com/maps/dir/牧歌の里+岐阜/三光稲荷神社+犬山",
        },
        {
          from: "三光稻荷神社",
          to: "東橫INN 機場",
          duration: "約 1 小時",
          mapUrl:
            "https://www.google.com/maps/dir/三光稲荷神社+犬山/東横INN中部国際空港1号館",
        },
      ],
    },
    {
      id: 6,
      date: "3/30",
      weekday: "週一",
      emoji: "🏠",
      title: "常滑散步 → 返台",
      color: "#3498DB",
      items: [
        {
          id: "d6_1",
          time: "09:00",
          type: "transport",
          emoji: "🚗",
          title: "還車",
          subtitle: "Times Car Rental 中部國際機場店",
          mapQuery: "タイムズカー 中部国際空港店",
          note: "",
        },
        {
          id: "d6_2",
          time: "上午",
          type: "activity",
          emoji: "🐱",
          title: "常滑陶瓷散步道 + Tokonyan 巨大招財貓",
          subtitle: "散步約 30-40 分・常滑燒文化街道",
          mapQuery: "とこにゃん 常滑市",
          note: "",
        },
        {
          id: "d6_3",
          time: "11:00",
          type: "transport",
          emoji: "🚌",
          title: "返回中部國際機場",
          subtitle: "搭公車 or 步行約 20 分 • 先辦 check-in",
          mapQuery: "中部国際空港 セントレア",
          note: "",
        },
        {
          id: "d6_4",
          time: "13:45",
          type: "transport",
          emoji: "✈️",
          title: "名古屋起飛（第 2 航廈）",
          subtitle: "CI-162 名古屋 → 台中 • 13:45出發",
          mapQuery: "中部国際空港 第2ターミナル",
          note: "",
        },
        {
          id: "d6_5",
          time: "16:05",
          type: "arrival",
          emoji: "🏠",
          title: "台中清泉崗機場抵達",
          subtitle: "平安回家！辛苦了大家 🎉",
          mapQuery: "台中清泉崗機場",
          note: "",
        },
      ],
      routes: [
        {
          from: "東橫INN 機場",
          to: "常滑陶瓷散步道",
          duration: "約 20 分",
          mapUrl:
            "https://www.google.com/maps/dir/東横INN中部国際空港1号館/とこにゃん+常滑市",
        },
        {
          from: "常滑陶瓷散步道",
          to: "中部國際機場",
          duration: "約 15 分",
          mapUrl:
            "https://www.google.com/maps/dir/とこにゃん+常滑市/中部国際空港",
        },
      ],
    },
  ],
};
